name: Auto Assign
on:
    workflow_call:

jobs:
    auto-assign:
        runs-on: ubuntu-latest
        steps:
            - uses: wow-actions/auto-assign@v3
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                reviewers: miskovicm
                numberOfReviewers: 1
                numberOfAssignees: 1
                skipKeywords: wip, draft
