name: Auto Assign
on:
    workflow_call:
        inputs:
            config_file:
                default: .github/auto-assign.yaml
                required: false
                type: string

jobs:
    run:
        runs-on: ubuntu-latest
        steps:
            - uses: wow-actions/auto-assign@v1
              with:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                CONFIG_FILE: ${{ inputs.config_file }}
